services:
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0.37
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}
